# Site settings
title: Web Designers in Melbourne - Cheap Website Design From Only $50
favicon-dir: favicon
url: http://cheapestwebsitesmelbourne.com.au
description: "The leading, innovative, cheapest and best Mobile Friendly Web Design company based in Melbourne Australia. Creating unique websites for leading businesses."
keywords: "Affordable website design in Australia, economical website, fast website, html5 design, budget website, cheap website designer, mobile friendly website, melbourne"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Cheapest Websites Melbourne powered by <a href="http://cheapestwebsitesmelbourne.com.au">CWM</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/messages/984371685029881
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

nav:
   - title: "Who We Are"
     url: "#about"
   - title: "What We Offer"
     url: "#quality"
   - title: "Why Us" 
     url: "#whyus"
   - title: "How to Order"
     url: "#download"
   - title: "Questions"
     url: "#faq"
   - title: "Get in Touch"
     url: "#contact"

form:
   - type: text
     name: Name
     size: 40
     maxlength: 250
   - type: text
     name: Email
     size: 40
     maxlength: 250
   - type: text
     name: Phone
     size: 40
     maxlength: 250

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
analytics :
    provider : google
    google :
        tracking_id : 'UA-63832785-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik


# Build settings
markdown: kramdown

permalink: pretty
email: admin@cheapestwebsitesmelbourne.com.au
phone: (03) 9005 5647
